### ISSUE TITLE
Events through proxy

### ISSUE THREAD

**Issue by SteveCrookJr** [lstern/SWProxy-plugins#52] opened 2016-08-16 18:19 UTC
Hi. I consistently use SWProxy (plugins) for my Swarfarm info, and I very consistently run into issues with events.

1st) Often, when I tap the Events icon in SW, nothing happens. At all. It just sits there. Occasionally the events screen will come up.
2nd) When I get into the events screen, tapping an event usually opens its details. Sometimes it fails.
3rd) If I get into an event detail, tapping on an event action either does nothing, or returns a parse error in SW. Very rarely does the action complete correctly.

All of these issues are resolved by swapping networks and bypassing SWProxy.

Just FYI.

**Comment by fperegrinvs** [comment] 2017-01-08 07:47
Sadly this is a problem with the proxy code we are using. This is a duplicate of #42

**Closed as completed by fperegrinvs** 2017-01-08 07:47 UTC
